# Generated by Django 5.0.2 on 2024-03-28 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                ("problem_id", models.AutoField(primary_key=True, serialize=False)),
                ("problem_name", models.CharField(max_length=250)),
                ("problem_link", models.URLField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="ProblemList",
            fields=[
                ("problem_set_id", models.AutoField(primary_key=True, serialize=False)),
                ("problem_set_name", models.CharField(max_length=250)),
                ("author", models.CharField(max_length=250)),
                ("link", models.URLField(blank=True, max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "problem_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.problem"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MarkedProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "problem_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.problem"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="problem",
            name="problem_set_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.problemlist"
            ),
        ),
    ]
