# Generated by Django 5.0.2 on 2024-04-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_markedproblem_problem_set_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="problem_difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                default="easy",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="problem",
            name="problem_type",
            field=models.CharField(default="-------", max_length=250),
        ),
    ]
