# Generated by Django 5.0.2 on 2024-04-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_problem_problem_difficulty"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="MarkedProblem",
        ),
    ]
