# Generated by Django 5.0.6 on 2024-05-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_status_options_status_problem_set_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemlist',
            name='problem_set_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
